"""Inspect examples generated by ReliabilityLab perturbations."""

from reliabilitylab.data import load_banking77
from reliabilitylab.perturbations import (
    perturb_texts,
)


PERTURBATIONS = [
    "typo",
    "char_delete",
    "word_delete",
    "case",
    "punctuation",
]


def main():

    dataset = load_banking77()

    samples = dataset["test"][
        "utterance"
    ][:10]

    for i, text in enumerate(
        samples,
        start=1,
    ):

        print("\n" + "=" * 70)
        print(f"EXAMPLE {i}")
        print("=" * 70)

        print(
            f"\nOriginal:\n{text}"
        )

        for perturbation in PERTURBATIONS:

            perturbed = perturb_texts(
                [text],
                perturbation=perturbation,
                seed=42,
            )[0]

            print(
                f"\n{perturbation}:"
            )

            print(
                perturbed
            )


if __name__ == "__main__":
    main()